title: Dougal Dobie # your name (or website title) here
logo: "/images/headshot_downsample.png"#?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  OzGrav Postdoctoral Research Fellow @ Swinburne
  <br><br>
  Radio Transients, Gravitational Waves
  <br><br>
  <div itemscope itemtype="https://schema.org/Person"><a itemprop="sameAs" content="https://orcid.org/0000-0003-0699-7019" href="https://orcid.org/0000-0003-0699-7019" target="orcid.widget" rel="noopener noreferrer" style="vertical-align:top;"><img src="https://orcid.org/sites/default/files/images/orcid_16x16.png" style="width:1em;margin-right:.5em;" alt="ORCID iD icon">ORCID</a></div>
  <a href = "mailto: ddobie@swin.edu.au"><img src="/images/email_glyph.png" style="width:1em;margin-right:.5em;">Email</a>
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
